name: datepicker
version: 0.1.5
author: João Furtado<jrofurtado@gmail.com>
description: Date Input using a Date Picker
homepage: https://github.com/jrofurtado/datepicker
dependencies:
  browser: any
  intl: any
  web_ui: any
